import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// COMPREHENSIVE ONTARIO BOAT RAMPS DATABASE
// Covering all major regions and waterways across Ontario

const ontarioRamps = [
  // ========================================
  // LAKE ONTARIO - TORONTO & GTA
  // ========================================
  {
    name: 'Bronte Harbour Boat Launch',
    lat: 43.3907,
    lng: -79.7003,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '2280 Ontario St, Oakville, ON L6L 2X8',
    description: 'Popular boat launch in Bronte Harbour with easy access to Lake Ontario. Features paved ramp and ample parking.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Port Credit Harbour Marina',
    lat: 43.5504,
    lng: -79.5869,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Lakeshore Rd E & Hurontario St, Mississauga, ON',
    description: 'Well-maintained launch ramp with full amenities. Access to Lake Ontario and Credit River.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Frenchman\'s Bay Marina',
    lat: 43.8074,
    lng: -79.0811,
    province: 'Ontario',
    type: 'trailer',
    fee: '$30',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '340 Bayly St W, Ajax, ON L1S 7K8',
    description: 'Full-service marina on Lake Ontario. Protected harbour with excellent facilities.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Bluffer\'s Park Marina',
    lat: 43.7063,
    lng: -79.2361,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '1 Brimley Rd S, Toronto, ON M1M 3W3',
    description: 'Scenic location below Scarborough Bluffs. Modern facilities and protected harbour.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Outer Harbour Marina',
    lat: 43.6290,
    lng: -79.3358,
    province: 'Ontario',
    type: 'trailer',
    fee: '$35',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Leslie St, Toronto, ON M4M 3H4',
    description: 'Large Toronto marina with multiple launch lanes. Can accommodate large vessels.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Whitby Harbour',
    lat: 43.8631,
    lng: -78.9392,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '1300 Victoria St W, Whitby, ON L1N 0A6',
    description: 'Protected harbour with good access to Lake Ontario. Popular fishing location.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Oshawa Harbour',
    lat: 43.8644,
    lng: -78.8508,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Oshawa, ON',
    description: 'Well-maintained harbour facilities. Access to central Lake Ontario.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // LAKE ONTARIO - EASTERN
  // ========================================
  {
    name: 'Cobourg Harbour',
    lat: 43.9607,
    lng: -78.1675,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Third St, Cobourg, ON K9A 5L5',
    description: 'Historic harbour with modern launch facilities. Great salmon fishing.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Port Hope Harbour',
    lat: 43.9567,
    lng: -78.2947,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Port Hope, ON',
    description: 'Charming harbour town with good boat launch. Access to Lake Ontario.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Trenton Marina',
    lat: 44.1028,
    lng: -77.5761,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Trenton, ON',
    description: 'Gateway to Bay of Quinte. Full-service marina at mouth of Trent River.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Belleville Bayshore Park',
    lat: 44.1639,
    lng: -77.3831,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Belleville, ON',
    description: 'Free launch on Bay of Quinte. Popular for walleye and bass fishing.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Picton Harbour',
    lat: 43.9939,
    lng: -77.1419,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Picton, ON K0K 2T0',
    description: 'Prince Edward County harbour. Gateway to Lake Ontario cruising.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // KINGSTON & THOUSAND ISLANDS
  // ========================================
  {
    name: 'Gananoque Municipal Marina',
    lat: 44.3273,
    lng: -76.1619,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '5 King St E, Gananoque, ON K7G 1E3',
    description: 'Gateway to the Thousand Islands. Full-service marina with excellent facilities.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Kingston - Portsmouth Harbour',
    lat: 44.2312,
    lng: -76.4860,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Kingston, ON',
    description: 'Historic Kingston harbour. Access to Lake Ontario and Rideau Canal.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Ivy Lea - Thousand Islands',
    lat: 44.3469,
    lng: -76.0561,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Ivy Lea, ON',
    description: 'Scenic launch in heart of Thousand Islands. Popular with island hoppers.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Rockport Boat Launch',
    lat: 44.3686,
    lng: -76.0694,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Rockport, ON',
    description: 'Small village launch with access to St. Lawrence River islands.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // OTTAWA RIVER & EASTERN ONTARIO
  // ========================================
  {
    name: 'Ottawa River - Britannia Park',
    lat: 45.3556,
    lng: -75.7981,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '2805 Carling Ave, Ottawa, ON K2B 7H7',
    description: 'Free public boat launch in Ottawa. Access to Ottawa River with beach nearby.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Petrie Island',
    lat: 45.4694,
    lng: -75.4978,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Trim Rd, Ottawa, ON',
    description: 'Popular Ottawa River launch. Great for water skiing and fishing.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Arnprior Boat Launch',
    lat: 45.4339,
    lng: -76.3500,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Arnprior, ON',
    description: 'Ottawa River access west of Ottawa. Good fishing for pike and bass.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Pembroke Marina',
    lat: 45.8167,
    lng: -77.1044,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Pembroke, ON',
    description: 'Upper Ottawa River access. Gateway to Allumette Island.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Cornwall - Lamoureux Park',
    lat: 45.0186,
    lng: -74.7403,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Cornwall, ON',
    description: 'St. Lawrence River access. Popular for bass tournaments.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // LAKE SIMCOE REGION
  // ========================================
  {
    name: 'Lake Simcoe - Jackson\'s Point',
    lat: 44.3047,
    lng: -79.2533,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Jackson\'s Point, ON',
    description: 'Popular ice fishing and summer boating location on Lake Simcoe.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Barrie - Tiffin Boat Launch',
    lat: 44.3894,
    lng: -79.6903,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Tiffin St, Barrie, ON',
    description: 'Free launch on Kempenfelt Bay. Very popular in summer.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Orillia - Port of Orillia',
    lat: 44.6086,
    lng: -79.4194,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Orillia, ON',
    description: 'Access to Lake Simcoe and Lake Couchiching. Full marina services.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Lagoon City Marina',
    lat: 44.5333,
    lng: -79.3000,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Lagoon City, ON',
    description: 'Private community marina on Lake Simcoe. Good facilities.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Beaverton Harbour',
    lat: 44.4347,
    lng: -79.1614,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Beaverton, ON',
    description: 'East shore of Lake Simcoe. Good fishing access.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // KAWARTHA LAKES
  // ========================================
  {
    name: 'Beavermead Park Boat Launch',
    lat: 44.2833,
    lng: -78.2836,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '1519 Ashburnham Dr, Peterborough, ON K9J 6X7',
    description: 'Free public boat launch on Little Lake. Great for fishing and recreational boating.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Bobcaygeon Lock',
    lat: 44.5417,
    lng: -78.5472,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Bobcaygeon, ON',
    description: 'Trent-Severn Waterway access. Scenic cottage country location.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Fenelon Falls Marina',
    lat: 44.5361,
    lng: -78.7428,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Fenelon Falls, ON',
    description: 'Beautiful falls location. Access to Sturgeon and Cameron Lakes.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Lindsay - Ken Reid Conservation Area',
    lat: 44.3583,
    lng: -78.7372,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Lindsay, ON',
    description: 'Sturgeon Lake access with conservation area amenities.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Buckhorn Lake Launch',
    lat: 44.5619,
    lng: -78.2625,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Buckhorn, ON',
    description: 'Access to Lower Buckhorn Lake. Popular fishing destination.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // MUSKOKA REGION
  // ========================================
  {
    name: 'Gravenhurst Bay',
    lat: 44.9186,
    lng: -79.3697,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Gravenhurst, ON',
    description: 'Gateway to Muskoka Lakes. Access to Lake Muskoka.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Bracebridge Bay',
    lat: 45.0411,
    lng: -79.3067,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Bracebridge, ON',
    description: 'Lake Muskoka access. Scenic Muskoka cottage country.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Huntsville - Fairy Lake',
    lat: 45.3306,
    lng: -79.2164,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Huntsville, ON',
    description: 'Downtown Huntsville lake access. Connects to larger Muskoka system.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Port Carling Locks',
    lat: 45.1181,
    lng: -79.5361,
    province: 'Ontario',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Port Carling, ON',
    description: 'Historic locks between Lake Muskoka and Lake Rosseau.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Bala Falls',
    lat: 45.0239,
    lng: -79.6353,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Bala, ON',
    description: 'Access to Lake Muskoka. Popular summer destination.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // GEORGIAN BAY
  // ========================================
  {
    name: 'Parry Sound - Town Dock',
    lat: 45.3389,
    lng: -80.0364,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Parry Sound, ON',
    description: 'Gateway to 30,000 Islands. Protected harbour on Georgian Bay.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Midland - Town Dock',
    lat: 44.7500,
    lng: -79.8833,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Midland, ON',
    description: 'Southern Georgian Bay access. Near Beausoleil Island.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Penetanguishene Harbour',
    lat: 44.7664,
    lng: -79.9311,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Penetanguishene, ON',
    description: 'Historic harbour with modern facilities. Georgian Bay Islands access.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Wasaga Beach',
    lat: 44.5217,
    lng: -80.0169,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Wasaga Beach, ON',
    description: 'World\'s longest freshwater beach. Nottawasaga Bay access.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Collingwood Harbour',
    lat: 44.5011,
    lng: -80.2161,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Collingwood, ON',
    description: 'Modern marina in revitalized harbour. Blue Mountain area.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Meaford Harbour',
    lat: 44.6064,
    lng: -80.5986,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Meaford, ON',
    description: 'Georgian Bay harbour with good facilities. Apple capital of Ontario.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Owen Sound - Harrison Park',
    lat: 44.5672,
    lng: -80.9428,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Owen Sound, ON',
    description: 'Head of Owen Sound Bay. Access to Georgian Bay.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Tobermory - Big Tub Harbour',
    lat: 45.2547,
    lng: -81.6656,
    province: 'Ontario',
    type: 'trailer',
    fee: '$30',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Tobermory, ON',
    description: 'North tip of Bruce Peninsula. Famous for shipwreck diving.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // LAKE HURON
  // ========================================
  {
    name: 'Bayfield Harbour Launch',
    lat: 43.5660,
    lng: -81.6969,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Main St, Bayfield, ON N0M 1G0',
    description: 'Scenic harbour launch with access to Lake Huron. Popular for fishing and sailing.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Goderich Harbour',
    lat: 43.7461,
    lng: -81.7186,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Goderich, ON',
    description: 'Canada\'s prettiest town. Large protected harbour on Lake Huron.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Kincardine Marina',
    lat: 44.1775,
    lng: -81.6361,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Kincardine, ON',
    description: 'Modern marina with excellent facilities. Scottish heritage town.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Southampton Beach',
    lat: 44.5006,
    lng: -81.3658,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Southampton, ON',
    description: 'Beautiful sandy beach with boat launch. Lake Huron access.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Saugeen River - Port Elgin',
    lat: 44.4333,
    lng: -81.3833,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Port Elgin, ON',
    description: 'River mouth launch to Lake Huron. Good salmon fishing.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Sarnia - Centennial Park',
    lat: 42.9753,
    lng: -82.4103,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Sarnia, ON',
    description: 'St. Clair River access. Great for watching freighters.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // LAKE ERIE
  // ========================================
  {
    name: 'Port Dover Harbour',
    lat: 42.7883,
    lng: -80.2017,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Port Dover, ON',
    description: 'Major Lake Erie fishing port. Excellent perch and walleye.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Port Stanley Marina',
    lat: 42.6667,
    lng: -81.2167,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Port Stanley, ON',
    description: 'Historic harbour village. Protected harbour on Lake Erie.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Port Burwell',
    lat: 42.6494,
    lng: -80.8147,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Port Burwell, ON',
    description: 'Small harbour with good fishing access. Lake Erie smallmouth bass.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Long Point - Port Rowan',
    lat: 42.6408,
    lng: -80.5247,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Port Rowan, ON',
    description: 'Access to Long Point Bay. World Biosphere Reserve.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Port Colborne - Sugarloaf Marina',
    lat: 42.8833,
    lng: -79.2500,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Port Colborne, ON',
    description: 'Welland Canal entrance. Access to Lake Erie.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Fort Erie - Niagara River',
    lat: 42.9100,
    lng: -78.9267,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Fort Erie, ON',
    description: 'Niagara River mouth. Strong currents, experienced boaters only.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // NIAGARA REGION
  // ========================================
  {
    name: 'Port Weller - St. Catharines',
    lat: 43.2167,
    lng: -79.2167,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'St. Catharines, ON',
    description: 'Welland Canal entrance on Lake Ontario side.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Port Dalhousie',
    lat: 43.2092,
    lng: -79.2608,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'St. Catharines, ON',
    description: 'Historic harbour with carousel. Lake Ontario access.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // NORTHERN ONTARIO - LAKE SUPERIOR
  // ========================================
  {
    name: 'Thunder Bay Marina',
    lat: 48.3822,
    lng: -89.2461,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Thunder Bay, ON',
    description: 'Lake Superior access with full marina amenities.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Sault Ste. Marie - Roberta Bondar Park',
    lat: 46.5167,
    lng: -84.3500,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Sault Ste. Marie, ON',
    description: 'St. Mary\'s River access. Watch freighters in the locks.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Marathon Marina',
    lat: 48.7519,
    lng: -86.3739,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Marathon, ON',
    description: 'Lake Superior north shore access. Remote and scenic.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Nipigon Bay Marina',
    lat: 49.0167,
    lng: -88.2667,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Nipigon, ON',
    description: 'Access to Lake Superior and Nipigon River. World-class brook trout.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // NORTHERN ONTARIO - INLAND
  // ========================================
  {
    name: 'Sudbury - Ramsey Lake',
    lat: 46.4906,
    lng: -80.9933,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Sudbury, ON',
    description: 'Large urban lake. Popular for walleye and pike.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'North Bay - Memorial Gardens',
    lat: 46.3117,
    lng: -79.4608,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'North Bay, ON',
    description: 'Lake Nipissing access. Excellent walleye and muskie fishing.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Callander Bay',
    lat: 46.2167,
    lng: -79.3667,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Callander, ON',
    description: 'South shore of Lake Nipissing. Good access and facilities.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Temagami Lake',
    lat: 47.0167,
    lng: -79.8000,
    province: 'Ontario',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Temagami, ON',
    description: 'Wilderness canoe country. Access to vast waterway network.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Timmins - Gillies Lake',
    lat: 48.4667,
    lng: -81.3333,
    province: 'Ontario',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Timmins, ON',
    description: 'Northern Ontario lake. Good pike and perch fishing.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // NORTHWESTERN ONTARIO
  // ========================================
  {
    name: 'Kenora - Norman Park',
    lat: 49.7676,
    lng: -94.4894,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Norman Park, Kenora, ON',
    description: 'Access to Lake of the Woods. Popular for fishing and exploring islands.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Sioux Narrows',
    lat: 49.4000,
    lng: -94.1333,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Sioux Narrows, ON',
    description: 'Lake of the Woods access. Premier walleye and muskie destination.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Nestor Falls',
    lat: 49.1333,
    lng: -93.9167,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Nestor Falls, ON',
    description: 'Remote Lake of the Woods access. Fly-in fishing outpost area.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Rainy River - Townsite',
    lat: 48.7167,
    lng: -94.5667,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Rainy River, ON',
    description: 'Rainy River access near US border. Excellent walleye fishing.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Fort Frances - LaPlace Rendez-Vous',
    lat: 48.6167,
    lng: -93.4000,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Fort Frances, ON',
    description: 'Rainy Lake access. Border town with good fishing.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // RIDEAU CANAL SYSTEM
  // ========================================
  {
    name: 'Rideau Canal - Ottawa Locks',
    lat: 45.4247,
    lng: -75.6967,
    province: 'Ontario',
    type: 'hand',
    fee: 'Free',
    parking: false,
    toilets: true,
    fourWD: false,
    address: 'Ottawa, ON',
    description: 'UNESCO World Heritage Site. Historic canal system.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Smiths Falls - Rideau Canal',
    lat: 44.9031,
    lng: -76.0267,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Smiths Falls, ON',
    description: 'Mid-point of Rideau Canal. Access to beautiful waterway.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Westport - Upper Rideau Lake',
    lat: 44.6769,
    lng: -76.3961,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Westport, ON',
    description: 'Upper Rideau Lake access. Scenic village on the canal.',
    source: 'ontario-gov',
    approved: true,
  },

  // ========================================
  // ADDITIONAL CENTRAL ONTARIO
  // ========================================
  {
    name: 'Rice Lake - Bewdley',
    lat: 44.1000,
    lng: -78.1667,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Bewdley, ON',
    description: 'Rice Lake access. Famous for walleye fishing.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Pigeon Lake - Bobcaygeon',
    lat: 44.5500,
    lng: -78.5500,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Bobcaygeon, ON',
    description: 'Large Kawartha lake with great fishing and cruising.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Haliburton - Head Lake',
    lat: 45.0500,
    lng: -78.5167,
    province: 'Ontario',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Haliburton, ON',
    description: 'Highland lake in cottage country. Clear waters and scenic beauty.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Minden - Gull Lake',
    lat: 44.9333,
    lng: -78.7167,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Minden, ON',
    description: 'Haliburton Highlands lake. Good bass and lake trout.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Bancroft - York River',
    lat: 45.0583,
    lng: -77.8556,
    province: 'Ontario',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Bancroft, ON',
    description: 'River access in mineral capital of Canada. Canoe routes.',
    source: 'ontario-gov',
    approved: true,
  },
]

const bcRamps = [
  {
    name: 'Deep Cove Boat Launch',
    lat: 49.3257,
    lng: -122.9483,
    province: 'BC',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Deep Cove, North Vancouver, BC',
    description: 'Scenic launch into Indian Arm. Popular for kayaking and small boats.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Horseshoe Bay Launch',
    lat: 49.3745,
    lng: -123.2713,
    province: 'BC',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Horseshoe Bay, West Vancouver, BC',
    description: 'Access to Howe Sound. Sheltered harbour with beautiful mountain views.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Okanagan Lake - Kelowna',
    lat: 49.8880,
    lng: -119.4960,
    province: 'BC',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Water St, Kelowna, BC',
    description: 'Prime Okanagan Lake access. Busy in summer with excellent facilities.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Shuswap Lake - Salmon Arm',
    lat: 50.7022,
    lng: -119.2750,
    province: 'BC',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Salmon Arm, BC',
    description: 'Popular houseboat destination. Wide launch ramp with good parking.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Harrison Lake - Harrison Hot Springs',
    lat: 49.2969,
    lng: -121.7844,
    province: 'BC',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Harrison Hot Springs, BC',
    description: 'Free public launch on beautiful Harrison Lake. Great for fishing.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Pitt Lake Launch',
    lat: 49.3208,
    lng: -122.6489,
    province: 'BC',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: false,
    fourWD: true,
    address: 'Pitt Meadows, BC',
    description: 'Remote launch requiring 4WD. Access to tidal freshwater lake.',
    source: 'osm',
    approved: true,
  },
  {
    name: 'Kootenay Lake - Balfour',
    lat: 49.6033,
    lng: -116.9231,
    province: 'BC',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Balfour, BC',
    description: 'Scenic mountain lake access. Popular for fishing and exploring.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Sproat Lake',
    lat: 49.2833,
    lng: -124.9167,
    province: 'BC',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Sproat Lake, BC',
    description: 'Vancouver Island lake known for warm water and petroglyphs.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Squamish Spit',
    lat: 49.6913,
    lng: -123.1584,
    province: 'BC',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Squamish, BC',
    description: 'Windsurfing and kiteboarding hotspot. Hand launch for small craft.',
    source: 'osm',
    approved: true,
  },
  {
    name: 'Cultus Lake Main Beach',
    lat: 49.0528,
    lng: -121.9750,
    province: 'BC',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Cultus Lake, BC',
    description: 'Popular summer destination with full amenities and lifeguards.',
    source: 'bc-gov',
    approved: true,
  },
]

async function main() {
  console.log('🚤 Starting comprehensive Ontario boat ramp seed...\n')

  // Clear existing data
  console.log('🗑️  Clearing existing data...')
  await prisma.ramp.deleteMany()
  await prisma.submission.deleteMany()
  console.log('✓ Database cleared\n')

  console.log('🏞️  Seeding Ontario ramps by region...')
  console.log('─────────────────────────────────────')

  let ontarioCount = 0
  for (const ramp of ontarioRamps) {
    await prisma.ramp.create({
      data: ramp,
    })
    ontarioCount++
  }

  console.log(`✓ Created ${ontarioCount} Ontario ramps`)
  console.log('  - Lake Ontario (GTA & Eastern)')
  console.log('  - Thousand Islands')
  console.log('  - Ottawa River')
  console.log('  - Lake Simcoe')
  console.log('  - Kawartha Lakes')
  console.log('  - Muskoka Region')
  console.log('  - Georgian Bay')
  console.log('  - Lake Huron')
  console.log('  - Lake Erie')
  console.log('  - Niagara Region')
  console.log('  - Lake Superior')
  console.log('  - Northern Ontario')
  console.log('  - Northwestern Ontario')
  console.log('  - Rideau Canal System')
  console.log('')

  console.log('🏔️  Seeding BC ramps...')
  let bcCount = 0
  for (const ramp of bcRamps) {
    await prisma.ramp.create({
      data: ramp,
    })
    bcCount++
  }
  console.log(`✓ Created ${bcCount} BC ramps\n`)

  const totalRamps = await prisma.ramp.count()
  console.log('═════════════════════════════════════')
  console.log(`✅ Seed complete! Total ramps: ${totalRamps}`)
  console.log(`   Ontario: ${ontarioCount}`)
  console.log(`   BC: ${bcCount}`)
  console.log('═════════════════════════════════════')
}

main()
  .catch((e) => {
    console.error('❌ Error during seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
