import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const ontarioRamps = [
  {
    name: 'Bronte Harbour Boat Launch',
    lat: 43.3907,
    lng: -79.7003,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '2280 Ontario St, Oakville, ON L6L 2X8',
    description: 'Popular boat launch in Bronte Harbour with easy access to Lake Ontario. Features paved ramp and ample parking.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Port Credit Harbour Marina',
    lat: 43.5504,
    lng: -79.5869,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Lakeshore Rd E & Hurontario St, Mississauga, ON',
    description: 'Well-maintained launch ramp with full amenities. Access to Lake Ontario and Credit River.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Beavermead Park Boat Launch',
    lat: 44.2833,
    lng: -78.2836,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '1519 Ashburnham Dr, Peterborough, ON K9J 6X7',
    description: 'Free public boat launch on Little Lake. Great for fishing and recreational boating.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Bayfield Harbour Launch',
    lat: 43.5660,
    lng: -81.6969,
    province: 'Ontario',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Main St, Bayfield, ON N0M 1G0',
    description: 'Scenic harbour launch with access to Lake Huron. Popular for fishing and sailing.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Gananoque Municipal Marina',
    lat: 44.3273,
    lng: -76.1619,
    province: 'Ontario',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '5 King St E, Gananoque, ON K7G 1E3',
    description: 'Gateway to the Thousand Islands. Full-service marina with excellent facilities.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Muskoka Falls Boat Launch',
    lat: 45.0376,
    lng: -79.3641,
    province: 'Ontario',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: false,
    fourWD: false,
    address: 'Muskoka Falls, ON',
    description: 'Natural boat launch for canoes and kayaks. Beautiful cottage country setting.',
    source: 'osm',
    approved: true,
  },
  {
    name: 'Lake Simcoe - Jackson\'s Point',
    lat: 44.3047,
    lng: -79.2533,
    province: 'Ontario',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Jackson\'s Point, ON',
    description: 'Popular ice fishing and summer boating location on Lake Simcoe.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Ottawa River - Britannia Park',
    lat: 45.3556,
    lng: -75.7981,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: '2805 Carling Ave, Ottawa, ON K2B 7H7',
    description: 'Free public boat launch in Ottawa. Access to Ottawa River with beach nearby.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Kenora - Norman Park',
    lat: 49.7676,
    lng: -94.4894,
    province: 'Ontario',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Norman Park, Kenora, ON',
    description: 'Access to Lake of the Woods. Popular for fishing and exploring islands.',
    source: 'ontario-gov',
    approved: true,
  },
  {
    name: 'Thunder Bay Marina',
    lat: 48.3822,
    lng: -89.2461,
    province: 'Ontario',
    type: 'trailer',
    fee: '$25',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Thunder Bay, ON',
    description: 'Lake Superior access with full marina amenities.',
    source: 'ontario-gov',
    approved: true,
  },
]

const bcRamps = [
  {
    name: 'Deep Cove Boat Launch',
    lat: 49.3257,
    lng: -122.9483,
    province: 'BC',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Deep Cove, North Vancouver, BC',
    description: 'Scenic launch into Indian Arm. Popular for kayaking and small boats.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Horseshoe Bay Launch',
    lat: 49.3745,
    lng: -123.2713,
    province: 'BC',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Horseshoe Bay, West Vancouver, BC',
    description: 'Access to Howe Sound. Sheltered harbour with beautiful mountain views.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Okanagan Lake - Kelowna',
    lat: 49.8880,
    lng: -119.4960,
    province: 'BC',
    type: 'trailer',
    fee: '$20',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Water St, Kelowna, BC',
    description: 'Prime Okanagan Lake access. Busy in summer with excellent facilities.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Shuswap Lake - Salmon Arm',
    lat: 50.7022,
    lng: -119.2750,
    province: 'BC',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Salmon Arm, BC',
    description: 'Popular houseboat destination. Wide launch ramp with good parking.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Harrison Lake - Harrison Hot Springs',
    lat: 49.2969,
    lng: -121.7844,
    province: 'BC',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Harrison Hot Springs, BC',
    description: 'Free public launch on beautiful Harrison Lake. Great for fishing.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Pitt Lake Launch',
    lat: 49.3208,
    lng: -122.6489,
    province: 'BC',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: false,
    fourWD: true,
    address: 'Pitt Meadows, BC',
    description: 'Remote launch requiring 4WD. Access to tidal freshwater lake.',
    source: 'osm',
    approved: true,
  },
  {
    name: 'Kootenay Lake - Balfour',
    lat: 49.6033,
    lng: -116.9231,
    province: 'BC',
    type: 'trailer',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Balfour, BC',
    description: 'Scenic mountain lake access. Popular for fishing and exploring.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Sproat Lake',
    lat: 49.2833,
    lng: -124.9167,
    province: 'BC',
    type: 'trailer',
    fee: '$10',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Sproat Lake, BC',
    description: 'Vancouver Island lake known for warm water and petroglyphs.',
    source: 'bc-gov',
    approved: true,
  },
  {
    name: 'Squamish Spit',
    lat: 49.6913,
    lng: -123.1584,
    province: 'BC',
    type: 'hand',
    fee: 'Free',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Squamish, BC',
    description: 'Windsurfing and kiteboarding hotspot. Hand launch for small craft.',
    source: 'osm',
    approved: true,
  },
  {
    name: 'Cultus Lake Main Beach',
    lat: 49.0528,
    lng: -121.9750,
    province: 'BC',
    type: 'trailer',
    fee: '$15',
    parking: true,
    toilets: true,
    fourWD: false,
    address: 'Cultus Lake, BC',
    description: 'Popular summer destination with full amenities and lifeguards.',
    source: 'bc-gov',
    approved: true,
  },
]

async function main() {
  console.log('Starting seed...')

  // Clear existing data
  console.log('Clearing existing data...')
  await prisma.ramp.deleteMany()
  await prisma.submission.deleteMany()

  console.log('Seeding Ontario ramps...')
  for (const ramp of ontarioRamps) {
    await prisma.ramp.create({
      data: ramp,
    })
  }
  console.log(`✓ Created ${ontarioRamps.length} Ontario ramps`)

  console.log('Seeding BC ramps...')
  for (const ramp of bcRamps) {
    await prisma.ramp.create({
      data: ramp,
    })
  }
  console.log(`✓ Created ${bcRamps.length} BC ramps`)

  const totalRamps = await prisma.ramp.count()
  console.log(`\n✓ Seed complete! Total ramps: ${totalRamps}`)
}

main()
  .catch((e) => {
    console.error('Error during seed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
